#!/bin/bash


PATH1=/Users/schuhmacher/bin

gdm=gdm_run_2D_0
SNA=SNA_2D_0
profils=profils

echo $SNA

mkdir -p lib

#Compilation sources
cd src
make clean
make

#Compilation gdm run
cd ../app
make clean
make

#Copie des executables
cd ..

echo " "
echo " "
echo "--- Copie des executables ---"
echo " "

echo "==================--======================="
echo "Copie vers : " $PATH1
echo "Executables a copier: $gdm / $SNA / $profils "
echo "==================--======================="

cp app/gdm_run/gdm_run $PATH1/$gdm
cp app/SNA/SNA $PATH1/$SNA
cp app/profils/profils $PATH1/$profils

echo "done"

