#!/bin/bash

PATH1=/Users/pat/Documents/Applications/bin


#Compilation sources
cd src
make

#Compilation gdm run
cd ../app
make

#Copie des executables
cd ../

echo " "
echo " "
echo "--- Copie des executables ---"
echo " "

echo "==========================================="
pwd
echo "==========================================="

echo " "
echo " "

cp app/gdm_run/gdm_run $PATH1/gdm_run_2D_0

cp app/SNA/SNA $PATH1/SNA_2D_0

